### ISSUE TITLE
BOM added to the beginning of CSL files

### ISSUE THREAD

**Issue by agruber** [citation-style-language/csl-editor-demo-site#15]
When I edit a citation style and then download it, \xFEFF (BOM) gets added to the beginning of the XML file. This causes trouble when parsing the XML file.

**Comment by rmzelle** [comment]
(@adam3smith, I don't know enough about BOM to know if or how this should be fixed.)

**Comment by adam3smith** [comment]
@agruber -- we've never had any problems with this and to the best of my knowledge BOM's are legal (if unnecesary, given the utf-8 declaration) in XML. In what situation is this causing parsing problems?

**Comment by agruber** [comment]
It made our citeproc-js crash. We have fixed it now on our end: we make sure that we remove the BOM. 

It's there to identify a file as being encoded in UTF-8. But the XML encoding is anyway given in <?xml version="1.0" encoding="UTF-8"?>.

None of the CSL files in https://github.com/citation-style-language/styles have it though.

**Comment by adam3smith** [comment]
> None of the CSL files in https://github.com/citation-style-language/styles have it though.

curious -- we've never checked for it, so something in our git process must strip it out. As I say above, I understand it's unnecessary, but it also shouldn't break things. Given that you're the only one reporting a problem with it and have fixed it I'm going to close this then -- I'd be open to revisiting if this is causing problems for other people, too.

**Comment by rmzelle** [comment]
Maybe this is relevant: http://xbiblio-devel.2463403.n2.nabble.com/CSL-test-suite-citeproc-js-migration-td7579462.html

> Style and locale inputs need to be presented in a consistent form: 
mixing serialized XML and XML DOM won't work (for example). This could 
be implemented without too much trouble if there is demand for it, but 
for the present, things need to be uniform.

(Frank is probably our DOM expert, so we can always ask him)
